# Generated by Django 4.0.5 on 2022-07-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('idDoctor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del doctor')),
                ('nombreDoc', models.CharField(max_length=50, verbose_name='Nombre del doctor')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('idPac', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del paciente')),
                ('nombrePac', models.CharField(max_length=25, verbose_name='Nombre del paciente')),
                ('apellidoPac', models.CharField(max_length=35, verbose_name='Apellido del paciente')),
                ('runPac', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('telefonoPac', models.IntegerField(max_length=9, verbose_name='Teléfono del paciente')),
                ('correoPac', models.CharField(max_length=20, verbose_name='Correo del paciente')),
            ],
        ),
    ]
