# Generated by Django 4.0.5 on 2022-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefonoPac',
            field=models.IntegerField(verbose_name='Teléfono del paciente'),
        ),
    ]
