# Generated by Django 4.0.5 on 2022-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_telefonopac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correoPac',
            field=models.CharField(max_length=40, verbose_name='Correo del paciente'),
        ),
    ]
