# Generated by Django 4.0.5 on 2022-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paciente_correopac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellido del paciente')),
                ('correo', models.EmailField(max_length=254)),
                ('telefonoPac', models.IntegerField(verbose_name='Teléfono del paciente')),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'agendar'], [1, 'cancelar'], [2, 'reprogramar']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
