# Generated by Django 4.0.5 on 2022-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Agendar'], [1, 'Cancelar'], [2, 'Reprogramar']]),
        ),
    ]
