# Generated by Django 4.0.5 on 2022-07-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=10),
        ),
    ]
