# Generated by Django 4.0.5 on 2022-07-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=35, verbose_name='Apellido del cliente'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefonoPac',
            field=models.IntegerField(verbose_name='Teléfono del cliente'),
        ),
    ]
